
require 'rake/testtask'

Rake::TestTask.new do |t|
	t.libs << ".."
	t.test_files = FileList[
		'test/class1.rb',
		'test/Nexp/test1.rb'
#		'test/db1.rb',
	]
#	t.pattern = "test/test*.rb";
#	t.verbose = true
end

Rake::TestTask.new("test-ccase") do |t|
	t.libs << ".."
	t.test_files = FileList[
		'test/ClearCase/add1.rb',
#		'test/ClearCase/view1.rb',
#		'test/ClearCase/view2.rb',
#		'test/ClearCase/vob1.rb'
	]
#	t.verbose = true
end
