
require 'rake/testtask'

Rake::TestTask.new do |t|
	t.libs << "test"
	t.test_files = FileList[
		'test/class2.rb',
		'test/Nexp/test1.rb'
#		'test/db1.rb',
	]
#	t.pattern = "test/test*.rb";
#	t.verbose = true
end
