
require 'rake/testtask'

Rake::TestTask.new do |t|
	t.libs << "../.."
	t.test_files = FileList[
		'class1.rb',
		'class2.rb',
		'Nexp/test1.rb'
#		'db1.rb',
	]
#	t.pattern = "*.rb";
#	t.verbose = true
end

Rake::TestTask.new("test:ccase") do |t|
	t.libs << "../.."
	t.test_files = FileList[
		'ClearCase/add1.rb',
#		'ClearCase/view1.rb',
#		'ClearCase/view2.rb',
#		'ClearCase/vob1.rb'
	]
end

Rake::TestTask.new("test:nexp") do |t|
	t.libs << "../.."
	t.test_files = FileList[
		'Nexp/test1.rb'
	]
end
