
source 'https://rubygems.org'
gem 'rake', '~>10.2'

# testing
gem 'minitest', '~>5.3'
# gem install rspec

# etc
gem 'nokogiri', '~>1.6'
gem 'rubyzip', '~>1.1'
gem 'rufus-mnemo', '~>1.2'
gem 'sqlite3', '~>1.3'
gem 'uuid', '~>2.3'
# gem install WikiCreole

# commander
gem 'ansi', '~>1.4'
gem 'commander', '~>4.2'
gem 'win32console', '~>1.3'

# debugging
gem 'byebug', '~>3.0'
# gem 'pry'
# gem 'pry-debugger' # need to be built with DevKit
